import {Metadata} from 'next'
import {cookies} from 'next/headers'
import React, {Suspense} from 'react'

import {AntdRegistry} from '@ant-design/nextjs-registry'

import {ColorModeContextProvider} from '@contexts/color-mode'
import '@refinedev/antd/dist/reset.css'
import {RefineContext} from '@/providers/refine-context'

export const metadata: Metadata = {
	title: 'Refine',
	description: 'Generated by create refine app',
	icons: {
		icon: '/icon.ico',
	},
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	const cookieStore = cookies()
	const theme = cookieStore.get('theme')
	const defaultMode = theme?.value === 'dark' ? 'dark' : 'light'
	return (
		<html lang="ru">
			<body>
				<Suspense>
					<AntdRegistry>
						<ColorModeContextProvider defaultMode={defaultMode}>
							<RefineContext>{children}</RefineContext>
						</ColorModeContextProvider>
					</AntdRegistry>
				</Suspense>
			</body>
		</html>
	)
}
